#!/bin/bash

MODEL_TYPE=${1:-lda}

if [ "$MODEL_TYPE" == "lda-test" ]
then
TOPIC_ARR=(20 45 70 100)
declare -i SUFFIX=0

for topic in ${TOPIC_ARR[@]};
do sbatch run-lda.sbatch $topic $SUFFIX
SUFFIX=$(( SUFFIX + 1 ))
done;

elif [ "$MODEL_TYPE" == "lda" ]
then

sbatch run-lda.sbatch

elif [[ "$MODEL_TYPE" == "dtm" || "$MODEL_TYPE" == "ldaseq" ]];
then
sbatch run-dtm.sbatch $MODEL_TYPE
elif [ "$MODEL_TYPE" == "dtm-test" ]
then
ITER_ARR=(30 50 100 500 1000)
TOPIC_ARR=(30 50 75 100)
SEED=8
declare -i SUFFIX=0

for iter in ${ITER_ARR[@]};
do for topic in ${TOPIC_ARR[@]};
do sbatch run-dtm-test.sbatch $iter $topic $SEED $SUFFIX;
SUFFIX=$(( SUFFIX + 1 ))
done;
done;

else
echo "Please specify a valid model type, not" $MODEL_TYPE
fi
